<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/styles/style.css">
    <title></title>
</head>
<body>
    <div class="container">
    <h1>Ceci est un gabarie</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, cum sequi quisquam eligendi iure ipsum dolore porro similique nesciunt commodi, nemo error, quam animi velit veritatis dolores magni sunt in.
    Corporis cumque inventore eos natus quis. Ad mollitia perspiciatis hic obcaecati cupiditate temporibus blanditiis similique iusto adipisci veniam nemo est eum, praesentium, ea minima sapiente provident voluptatum quibusdam quia eos?
    Magnam aperiam odio quod illo illum facilis velit, at neque eaque, eos magni ipsum consequuntur sint repellendus quisquam, eligendi similique labore quas omnis nisi hic recusandae? Dicta qui quasi doloribus.</p>
    </div>
</body>
</html>